<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    <AssemblyTitle>STORM PS4 PKG SENDER 1.4.0</AssemblyTitle>
    <Product>STORM PS4 PKG SENDER 1.4.0</Product>
    <Title>STORM PS4 PKG SENDER 1.4.0</Title>
    <Description>STORM PS4 PKG SENDER Installer</Description>
    <Company>ReiKatari</Company>
    <Authors>ReiKatari</Authors>
    <Copyright>Copyright © 2026 STORM TEAM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\dist\STORM PS4 PKG SENDER.exe" Link="Payload\STORM PS4 PKG SENDER.exe" Condition="Exists('..\..\dist\STORM PS4 PKG SENDER.exe')" />
    <EmbeddedResource Include="..\..\Files\STORM_Certificate.cer" Link="Payload\STORM_Certificate.cer" Condition="Exists('..\..\Files\STORM_Certificate.cer')" />
    <EmbeddedResource Include="AppIcon.ico" Link="Payload\AppIcon.ico" Condition="Exists('AppIcon.ico')" />
    <EmbeddedResource Include="logo.png" Link="Payload\logo.png" Condition="Exists('logo.png')" />
    <EmbeddedResource Include="..\..\tools\**" Link="Payload\tools\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
